"""Add secret table

Revision ID: 7d84943a8de7
Revises: 612b76967a81
Create Date: 2022-12-08 19:59:13.879077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d84943a8de7'
down_revision = '612b76967a81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(none_as_null=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_id'), 'secret', ['id'], unique=True)
    op.create_index('ix_ssk', 'secret', ['service', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ssk', table_name='secret')
    op.drop_index(op.f('ix_secret_id'), table_name='secret')
    op.drop_table('secret')
    # ### end Alembic commands ###
