# Config sections
CONFIG_SECTION_SCIUROMORPHA = "sciuromorpha"
CONFIG_SECTION_DATABASE = "db"
CONFIG_SECTION_MESSAGEQUEUE = "mq"

# Config ENV variables.
ENV_CONFIG_PREFIX = "SCIUROMORPHA_"
ENV_CONFIG_MODE = ENV_CONFIG_PREFIX + "MODE"
ENV_CONFIG_FILE = ENV_CONFIG_PREFIX + "CONFIG"
ENV_CONFIG_FILES = ENV_CONFIG_PREFIX + "CONFIG_FILES"

# Enviroment modes.
ENV_MODE_DEVELOPMENT = "development"
ENV_MODE_PRODUCTION = "production"
ENV_MODE_TEST = "test"

# Meta data keys.
META_KEY_STUB = "_"
META_KEY_ORIGIN_URL = "origin_url"
